name: segment_flutter_sdk
description: A Flutter plugin that allows sending analytics events to https://segment.com
version: 1.0.0
author: Jon Duran <jonyas@gmail.com>
homepage: https://github.com/freska-fi/segment_flutter_sdk

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  meta: ^1.1.7
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: net.freska.segmentfluttersdk
    pluginClass: SegmentFlutterSdkPlugin
